feat: Add `reuseInteractions` option to `CommandHandler`
discord-rose/discord-rose pull request #22
Opened 2021-05-23 03:50 UTC by BR88C

This adds a `reuseInteractions` option to the command handler. If it is set to `true`, instead of overwriting all commands for an application, it will delete, update, and add them as needed. This is useful when working with global commands, as bulk overwrites cause all cached commands to become invalid, whereas this method will preserve commands with unchanged interaction data. A real-world use for this would be faster rollouts of bot updates that don't change interaction data, as currently a bot update would result in global slash commands being unavailable for a considerable amount of time.

Additionally to make this work, `InteractionResource` has 3 new methods; `.get()` (https://github.com/discord-rose/discord-rose/commit/562152f318abc88e7e89ee9eedb7c4b2809d92fb A `GET` request that retrieves all commands for an application. Also, I pulled an oopsies and accidentally labeled the commit as `.set()`, sorry 🤪), `.delete()` (https://github.com/discord-rose/discord-rose/commit/4f81642c308991105a8045c0a8820769a2af23e4 A `DELETE` request that will delete a specified command), and `.add()` (https://github.com/discord-rose/discord-rose/commit/5d43b504f964306545c6a070bc8f5fe8c6ec1184 A `POST` request that adds a new command to the application). However, the naming scheme of these methods is a little odd, and may need to be refactored. Additionally, the method I'm using to find changed commands is a little janky, so please let me know if there is a cleaner way to go about it. Typings in `src/rest/resources/Interactions.ts` for the pre-existing methods have also changed (Not breaking) to better match the typings in `discord-api-types`.

2021-05-23 04:05 UTC, jpbberry requested changes

2021-05-23 04:05 UTC, jpbberry commented on src/structures/CommandHandler.ts
> +          console.log(changedInteractions)
Leftovers

2021-05-23 04:25 UTC, BR88C commented on src/structures/CommandHandler.ts
> +          console.log(changedInteractions)
My bad, fixed 69a0385

2021-05-23 10:02 UTC, jpbberry commented
Please address the action lint errors

2021-05-23 15:19 UTC, BR88C commented
> Please address the action lint errors

Done bb823f3

2021-05-23 18:36 UTC, BR88C commented
6221904 - Fixed the `InteractionResource.update()` method, as it accepted an interaction name, which caused an error to be thrown. Note that this will cause breaking changes due to syntax modification. `CommandHandler.add()` has also been modified so that commands added after the initial interactions setup will now be properly set.

ca961c6 - Cleaned up JSDoc comments for `InteractionResource`.

2021-05-24 13:59 UTC, BR88C commented
Was doing some testing, found some edge cases and resolved them in 540f3de. e20ffcc adds a `traverseObject()` utility function that's used when resolving the edge cases in nested interaction options.

2021-05-24 15:56 UTC, jpbberry approved these changes

2021-05-25 02:36 UTC, jpbberry commented on src/structures/CommandHandler.ts
> +    reuseInteractions: false
Default this to true

2021-05-27 18:58 UTC, merged